# Generated by Django 4.1.6 on 2023-02-27 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_num', models.CharField(max_length=200)),
                ('prod_des', models.CharField(max_length=500)),
                ('prod_stock', models.BigIntegerField()),
                ('prod_price', models.FloatField()),
                ('prod_image', models.ImageField(default='', upload_to='product/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.seller')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
