# Generated by Django 4.1.6 on 2023-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('e_mail', models.CharField(max_length=50)),
                ('ph_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='customer/')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('acc_no', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('acc_holder_name', models.CharField(max_length=50)),
                ('ph_num', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='seller/')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
